spring:
  ai:
    openai:
      base-url: https://chatapi.littlewheat.com
      api-key: sk-OwJ9nvwd3qRbkaNTSVp9zJaKKma0lnOWqjngtUdR2erOPcoD
      chat:
        options:
          model: gpt-3.5-turbo